// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWmV3IJRWvf3IUV727uptKEnOxADCcco',
    appId: '1:260011829307:web:a451c12f078f8617ba941e',
    messagingSenderId: '260011829307',
    projectId: 'paylas-f4c19',
    authDomain: 'paylas-f4c19.firebaseapp.com',
    storageBucket: 'paylas-f4c19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOt88STE5ZQAthQgxAy0qw9BcxM515qU',
    appId: '1:260011829307:android:4275fd4165044087ba941e',
    messagingSenderId: '260011829307',
    projectId: 'paylas-f4c19',
    storageBucket: 'paylas-f4c19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ifUkM2B6FWS8ox_wpLPYFkO_oWVcm4c',
    appId: '1:260011829307:ios:1cb99cf6fdb0b275ba941e',
    messagingSenderId: '260011829307',
    projectId: 'paylas-f4c19',
    storageBucket: 'paylas-f4c19.firebasestorage.app',
    iosBundleId: 'com.ebaysoft.paylas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ifUkM2B6FWS8ox_wpLPYFkO_oWVcm4c',
    appId: '1:260011829307:ios:1cb99cf6fdb0b275ba941e',
    messagingSenderId: '260011829307',
    projectId: 'paylas-f4c19',
    storageBucket: 'paylas-f4c19.firebasestorage.app',
    iosBundleId: 'com.ebaysoft.paylas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOWmV3IJRWvf3IUV727uptKEnOxADCcco',
    appId: '1:260011829307:web:952bfc0d0b78621bba941e',
    messagingSenderId: '260011829307',
    projectId: 'paylas-f4c19',
    authDomain: 'paylas-f4c19.firebaseapp.com',
    storageBucket: 'paylas-f4c19.firebasestorage.app',
  );
}
